HB-01
engineer027/Cinema pull request #1
Opened 2021-01-26 12:31 UTC by engineer027

configured pom;

2021-01-26 15:26 UTC, sanek98cv approved these changes

2021-01-26 15:26 UTC, sanek98cv commented on pom.xml
> +        </dependency>
Don’t add dependencies that you don’t use to pom.xml;
чеклист

2021-01-27 08:13 UTC, Sofasmile requested changes

2021-01-27 08:13 UTC, Sofasmile commented on pom.xml
>  </project>
let's add an empty line at the end of the file

2021-01-27 08:13 UTC, Sofasmile commented on src/main/java/com/dev/cinema/dao/impl/MovieDaoImpl.java
> +            movie.setId(itemId);
https://mate-academy.github.io/jv-program-fulltime/03_hibernate/checklist/hibernate_01.html

2021-01-27 08:13 UTC, Sofasmile commented on src/main/java/com/dev/cinema/dao/impl/MovieDaoImpl.java
> +            throw new RuntimeException("Can't insert Movie entity ", e);
```suggestion
            throw new DataProcessingException("Can't insert Movie entity " + movie, e);
```

2021-01-27 08:13 UTC, Sofasmile commented on src/main/resources/hibernate.cfg.xml
> +</hibernate-configuration>
add empty line

2021-01-27 10:50 UTC, RomanDubovskyi approved these changes

2021-01-28 08:19 UTC, merged