Spring 07
engineer027/Cinema pull request #10
Opened 2021-02-17 13:56 UTC by engineer027

2021-02-17 14:08 UTC, YuraBondarenko approved these changes

2021-02-17 14:08 UTC, YuraBondarenko commented on src/main/java/com/dev/cinema/annotation/LoginValidator.java
> +    public boolean isValid(String contactField,
ckecklist
`Don’t forget to rename parameters in isValid() method.`

2021-02-17 14:10 UTC, YuraBondarenko reviewed
also delete class HashUtil

2021-02-18 08:51 UTC, KseniiaMakarova requested changes

2021-02-18 08:51 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/annotation/FieldsValueMatch.java
> +
redundant empty line

2021-02-18 08:51 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/annotation/FieldsValueMatchValidator.java
> +
same

2021-02-18 08:51 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/annotation/FieldsValueMatchValidator.java
> +
same

2021-02-18 08:51 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/annotation/LoginValidator.java
> +
same

2021-02-18 08:51 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/annotation/LoginValidator.java
> +    }
we can remove this

2021-02-18 08:51 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/annotation/LoginValidator.java
> +
redundant empty line

2021-02-18 08:51 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/dto/MovieSessionRequestDto.java
> +    @Min(1)
wrappers are not supported by this annotation

2021-02-18 08:51 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/dto/MovieSessionRequestDto.java
> +    @Min(1)
same

2021-02-18 08:51 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/dto/CinemaHallRequestDto.java
> +import com.sun.istack.NotNull;
```suggestion
import javax.validation.constraints.NotNull;
```
same for all requestDtos

2021-02-18 10:05 UTC, KseniiaMakarova requested changes

2021-02-18 10:05 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/dto/MovieSessionRequestDto.java
> +    @Size(min = 1)
please see the javadoc 
https://docs.oracle.com/javaee/6/api/javax/validation/constraints/Size.html

are wrappers supported?

2021-02-18 10:05 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/dto/MovieRequestDto.java
> +import com.sun.istack.NotNull;
what about this?

2021-02-18 10:05 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/dto/UserRegistrationDto.java
> +import com.sun.istack.NotNull;
same

2021-02-18 11:09 UTC, KseniiaMakarova approved these changes

2021-02-18 11:09 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/dto/MovieSessionRequestDto.java
>  import com.sun.istack.NotNull;
?

2021-02-18 12:23 UTC, merged