Spring 08
engineer027/Cinema pull request #11
Opened 2021-02-18 22:22 UTC by engineer027

2021-02-19 10:30 UTC, YuraBondarenko approved these changes

2021-02-22 08:58 UTC, Sofasmile requested changes

2021-02-22 08:58 UTC, Sofasmile commented on src/main/java/com/dev/cinema/config/SecurityConfig.java
> +                .userDetailsService((userDetailsService));
we should add here passwordEncoder

2021-02-22 08:58 UTC, Sofasmile commented on src/main/java/com/dev/cinema/config/SecurityConfig.java
> +                .antMatchers(HttpMethod.POST, "/register").permitAll()
let's add more urks here

2021-02-22 08:58 UTC, Sofasmile commented on src/main/java/com/dev/cinema/controllers/InjectData.java
> +public class InjectData {
let's rename this class to DataInitializer and use the annotation Component instead of Controller

2021-02-22 08:58 UTC, Sofasmile commented on src/main/java/com/dev/cinema/controllers/InjectData.java
> +        roleService.add(admin);
let's create one admin user here too

2021-02-22 08:58 UTC, Sofasmile commented on src/main/java/com/dev/cinema/dao/impl/UserDaoImpl.java
> +                    .createQuery("SELECT u FROM User u left join fetch u.roles "
why do we use left join here? is it possible to get user without role?

2021-02-22 08:58 UTC, Sofasmile commented on src/main/java/com/dev/cinema/model/User.java
> +    private List<Role> roles;
let's use set instead of the list

2021-02-22 08:58 UTC, Sofasmile commented on src/main/java/com/dev/cinema/model/User.java
> +            }
???

2021-02-22 08:58 UTC, Sofasmile commented on src/main/java/com/dev/cinema/model/dto/UserRegistrationDto.java
> +    private List<String> roles;
let's set USER role by default to all users at the method register()

2021-02-22 08:58 UTC, Sofasmile commented on src/main/java/com/dev/cinema/security/AuthenticationServiceImpl.java
> +        user.setPassword(passwordEncoder.encode(user.getPassword()));
we should encode password at the userService layer
and here we can set USER role by default to all users

2021-02-22 08:58 UTC, Sofasmile commented on src/main/java/com/dev/cinema/security/CustomUserDetailsService.java
> +                -> new RuntimeException("Could not find user by login" + login));
let's throw here "...specific Spring exception when user is not found by username"
https://mate-academy.github.io/jv-program-fulltime/04_spring/checklist/hw_08.html

2021-02-22 08:58 UTC, Sofasmile commented on src/main/java/com/dev/cinema/security/CustomUserDetailsService.java
> +        userBuilder.roles(user.getRoles().toString());
does `user.getRoles().toString()` work correctly?

2021-02-22 12:38 UTC, Sofasmile requested changes

2021-02-22 12:38 UTC, Sofasmile commented on src/main/java/com/dev/cinema/model/dto/UserRegistrationDto.java
> +    private Set<String> roles;
не варто в UserRegistrationDto приймати ролі, роль USER варто засечувати в методі /register

2021-02-22 15:20 UTC, Sofasmile approved these changes

2021-02-22 15:32 UTC, merged