HB-5
engineer027/Cinema pull request #3
Opened 2021-02-02 13:44 UTC by engineer027

2021-02-02 16:39 UTC, oleksandrdziubiuk approved these changes

2021-02-02 16:39 UTC, oleksandrdziubiuk commented on src/main/java/com/dev/cinema/model/User.java
> +                + ", password='" + password + '\'' + '}';
думаю пароль краще не виводити на екран

2021-02-02 16:39 UTC, oleksandrdziubiuk commented on src/main/java/com/dev/cinema/util/HashUtil.java
> +    public HashUtil() {
конструктор здається треба приватним робити

2021-02-02 17:02 UTC, KseniiaMakarova requested changes

2021-02-02 17:02 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/dao/impl/UserDaoImpl.java
> +
redundant empty line

2021-02-02 17:02 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/User.java
> +                + ", password='" + password + '\'' + '}';
good point from Oleksandr

2021-02-02 17:02 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/service/impl/UserServiceImpl.java
> +        return userDao.findByLogin(email);
let's use either `login` or `email`
check out the UML for this project

2021-02-02 17:02 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/security/AuthenticationServiceImpl.java
> +        String hashPassword = HashUtil.hashPassword(password, userFromDB.get().getSalt());
is it safe to execute this line?

2021-02-02 17:02 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/util/HashUtil.java
> +    public HashUtil() {
I agree

2021-02-03 07:46 UTC, KseniiaMakarova requested changes

2021-02-03 07:46 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/security/AuthenticationService.java
> +    User register(String email, String password);
```suggestion
    User login(String login, String password) throws AuthenticationException;

    User register(String login, String password);
```

2021-02-03 07:46 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/service/UserService.java
> +    Optional<User> findByEmail(String login);
```suggestion
    User add(User user);

    Optional<User> findByLogin(String login);
```

2021-02-03 08:08 UTC, KseniiaMakarova approved these changes

2021-02-03 08:52 UTC, merged