Spring 05
engineer027/Cinema pull request #8
Opened 2021-02-12 19:37 UTC by engineer027

2021-02-14 20:23 UTC, Ilya-brinchuk approved these changes

2021-02-15 09:10 UTC, KseniiaMakarova requested changes

2021-02-15 09:10 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/controllers/MovieSessionController.java
> +@RequestMapping(" /movie-sessions")
```suggestion
@RequestMapping("/movie-sessions")
```

2021-02-15 09:10 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/controllers/MovieSessionController.java
> +                                                            LocalDate date) {
```suggestion
    public List<MovieSessionResponseDto> findAvailableSessions(
                                      @RequestParam Long movieId,
                                      @RequestParam @DateTimeFormat(pattern = "dd.MM.yyyy")
                                      LocalDate date) {
```
let's try to make this more readable

2021-02-15 09:10 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/controllers/MovieSessionController.java
> +    public void delete(@RequestBody MovieSessionDeleteDto movieSessionDeleteDto) {
please see this thread - https://mateacademy.slack.com/archives/G01EHB8CWAE/p1613330083125300

2021-02-15 09:10 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/dao/MovieSessionDao.java
> +    MovieSession delete(MovieSession movieSession);
```suggestion
    void delete(Long movieSessionId);
```

2021-02-15 09:10 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/dao/impl/MovieSessionDaoImpl.java
> +            session.delete(movieSession);
let's use load() method to get the session by id before deleting it

2021-02-15 09:10 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/dto/MovieSessionDeleteDto.java
> +public class MovieSessionDeleteDto {
let's remove this

2021-02-15 09:10 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/dto/MovieSessionRequestDto.java
> +    private LocalDateTime showTime;
how can you pass LocalDateTime in json?

2021-02-15 09:10 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/dto/MovieSessionResponseDto.java
> +    private Movie movie;
let's not fill the Dto with entity - use movieId instead

2021-02-15 09:10 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/dto/MovieSessionResponseDto.java
> +    private Long cinemaHallId;
what about showTime?

2021-02-15 09:10 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/dto/MovieSessionUpdateDto.java
> +    private LocalDateTime showTime;
how can you pass LocalDateTime in json?

2021-02-15 09:10 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/service/mapper/CinemaHallMapperImpl.java
> +public class CinemaHallMapperImpl implements CinemaHallMapper {
we don't really need interfaces for these mappers - let's remove the interfaces
```suggestion
public class CinemaHallMapper {
```

2021-02-15 09:10 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/service/mapper/CinemaHallMapperImpl.java
> +        cinemaHallResponseDto.setCapacity(cinemaHallResponseDto.getCapacity());
is this line ok?

2021-02-15 09:10 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/service/mapper/MovieSessionMapperImpl.java
> +    public MovieSession mapDeleteDtoToMovieSession(MovieSessionDeleteDto movieSessionDeleteDto) {
let's remove this method

2021-02-15 11:39 UTC, KseniiaMakarova requested changes

2021-02-15 11:39 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/controllers/MovieSessionController.java
> +
redundant empty line

2021-02-15 11:39 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/service/mapper/CinemaHallMapperImpl.java
> +        cinemaHallResponseDto.setCapacity(cinemaHallResponseDto.getCapacity());
again, it is something wrong with this line

2021-02-15 11:39 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/service/mapper/CinemaHallMapperImpl.java
> +public class CinemaHallMapperImpl {
```suggestion
public class CinemaHallMapper {
```
same for all mappers

2021-02-15 12:00 UTC, KseniiaMakarova approved these changes

2021-02-15 18:20 UTC, merged